### ISSUE TITLE
Mismatch between documentation and implementation...

### ISSUE THREAD

**Issue by mpegram3rd** [mykle1/MMM-BMW-OW#1]
There was a minor issue that made this module not work for me when I pulled it down.

I did some digging into it and it appears that the problem is that the code expects 2 items to come from config which get added into the URL (see: `node_helper.js` line 21 )

- `language` is not documented in the `README.md` so I wasn't aware it should be set
- `api` is represented as `apiKey` in the `README.md`

When I set those two values in my `config.js` the module worked fine.    It seems like the "easy"  option here is to just make a minor update to the `README.md`

Thanks for your time in writing this module!

**Comment by mykle1** [comment]
The module should read the language from your config.js file (at the beginning). So, there is no need to set a config option for the module itself

**Comment by mykle1** [comment]
I have changed the README to reflect api instead of apiKey in the config entry. I am sorry for the oversight and I thank you for bringing it to my attention
