### ISSUE TITLE
Not working - its just shows loading

### ISSUE THREAD

**Issue by hriday-khurana** [mykle1/MMM-BMW-OW#2]
![image](https://user-images.githubusercontent.com/60769531/83206534-19f89100-a11f-11ea-8841-ed5497525625.png)
i loaded this module. all other weather module are working fine but this one just says "OpenWeather data..."
it doesnt show any data.

Let me know what logs and from where i need to provide you. I am not experience with code structure of this. 

Check bottom_bar in attached snapshot

**Comment by mykle1** [comment]
It is likely a problem with your config entry. I just installed again to test and it fires right up. Try using the default entry from the repo and put in your api key and see what happens. If you need more help please post on the forum. It's easier for me to troubleshoot there, thanks.

**Comment by hriday-khurana** [comment]
i identified with help of 1st reported issue that you have incorrect documentation, your apiKey variable you asking to add in config files doesn't match with the variable you using in MMM-BMW-OW.js or node_helper.js file.

I think that's what needs to be corrected in this article to update "Config.js entry and options" section so that its referring the correct variable name which is used for calling in other files. 

Thanks for your response!!
i am not sure which forum you are referring so provided my inputs here.

**Comment by mpegram3rd** [comment]
Yes.. it's the mismatch between documentation saying `apiKey` and the code actually expecting it to be called `api`  You're having the exact problem I had.

**Comment by mykle1** [comment]
I have changed the readMe to reflect api instead of apiKey. I am sorry for the oversight and I thank you both for bringing that to my attention
