### ISSUE TITLE
hello dear 

### ISSUE THREAD

**Issue by juntran187** [mykle1/MMM-BMW-OW#3]
First : I want to thank you very much for your modules. it's amazing .
Second : I want to ask you a question about the high and low of the daily temperature. High temperatures are correct. low temperatures are not accurate. How can i fix that ?

**Comment by mykle1** [comment]
Thank you for you kind words.

The temps are coming directly from the API (OpenWeather) data. This cannot be changed unless you code it to make adjustments to the data coming from the api.
