### ISSUE TITLE
If "No Rain" undefined message is returned.

### ISSUE THREAD

**Issue by scumbelly** [mykle1/MMM-BMW-OW#4]
Hi,
I added  + forecast.daily[0].rain + "/mm Rain" to the MMM-BM-OW module and if there is rain the amount is returned.  If there is no rain I receive "undefined".  I would like to show " 0 " - zero or something but I haven't been able to figure out how to translate, use a isNaN(value) or a bunch of other 'down that rabbit hole' ideas.  Is this at all possible?

Cheers.

**Comment by mykle1** [comment]
This is not an issue so I am closing this
