### ISSUE TITLE
Openweather OneCall API problem

### ISSUE THREAD

**Issue by DennisEJ** [mykle1/MMM-BMW-OW#6]
Hello all... I tried putting the Open Weather OneCall API in my mirror... when I got it all in, I ran npm config:check and it said I didn't have any configuration errors.. But when I start the MM,  nothing show up in the area (upper right) where I had the old weather showing up.. Here is the openweather script that I'm using. Maybe one of you can spot what I'm doing wrong in this line.

weatherProvider: "https//:api.openweathermap.org/data/2.5/onecall?lat={37.971} &lon={122.398} &exclude=minutely &appid={425dxxxxxxxxxxxxxxxxxxxxx3}",

Thanks all...
Dennis

**Comment by mykle1** [comment]
I think you've mistaken this repo for the forum. Repost your issue there
